### ISSUE TITLE
Handle upper-case organisation/repo-owner names in a better way

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-sandbox/keptn-service-template-go#118]
When using this template with a username that has uppercase characters, e.g., @Raffy23, we ended up getting problems when pushing to `ghcr.io` using the following workflow:

https://github.com/keptn-sandbox/keptn-service-template-go/blob/d1b3d39f9b5c635c34acf3fcb32f0c909c15b21d/.github/workflows/CI.yml#L130-L139

This was partially addressed in keptn/gh-automation (see PRs [#20](https://github.com/keptn/gh-automation/pull/20), [#18](https://github.com/keptn/gh-automation/pull/18), [#15](https://github.com/keptn/gh-automation/pull/15)), but it's still not a very satisfying solution as it adds complexity to keptn/gh-automation.

According to [docker-build-push-action Troubleshooting](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md#repository-name-must-be-lowercase), a better solution would be to sanitize the repo owner directly in your workflow:

```yaml
- name: Sanitize repo owner
  uses: actions/github-script@v4
  id: repo_slug
  with:
    result-encoding: string
    script: return '${{ github.repository_owner }}'.toLowerCase()

- name: Build and push
  uses: docker/build-push-action@v2
  with:
    context: .
    push: true
    tags: ghcr.io/${{ steps.repo_slug.outputs.result }}/${{ env.IMAGE }}:${{ env.VERSION }}
```

# Definition of done

- [ ] Sanitize `repository_owner` in all affected workflows in keptn-service-template-go, and use sanitized string instead of `github.repository_owner`
- [ ] Proof that it works using upper-cased GitHub username and provide screenshots

**Affected Workflows**

* CI - https://github.com/keptn-sandbox/keptn-service-template-go/blob/main/.github/workflows/CI.yml
* Pre-Release - https://github.com/keptn-sandbox/keptn-service-template-go/blob/main/.github/workflows/pre-release.yml
* Release - https://github.com/keptn-sandbox/keptn-service-template-go/blob/main/.github/workflows/release.yml
