### ISSUE TITLE
Update the deployment manifest

### ISSUE THREAD

**Issue by johannes-b** [keptn-sandbox/keptn-service-template-go#21]
The deployment manifest https://github.com/keptn-sandbox/keptn-service-template-go/blob/master/deploy/service.yaml is not aligned with the best-practices we are currently following. 

**Improvements:**
- [ ] Remove the namespace since Keptn can run in namespaces other than `keptn` -> Update the Readme here: https://github.com/keptn-sandbox/keptn-service-template-go#installation
- [ ] Add recommended Kubernetes labels like: 
```
  labels:
    app.kubernetes.io/name: keptn-service-xyz
    app.kubernetes.io/instance: keptn
    app.kubernetes.io/part-of: keptn
    app.kubernetes.io/component: execution-plane
    app.kubernetes.io/version: 0.0.1
``` 
- [ ] Add a default Role/ServiceAccount/RoleBinding
